### ISSUE TITLE
Can it handle private repo?  How about conflict ? 

### ISSUE THREAD

**Issue by Fred-Vatin** [Shakeskeyboarde/mknew#2]
Hi,

1. Can it copy folder from github private repo ?
2. How does it handle conflict if a downloaded file already exists in the working dir ? Is there an option to skip it, overwrite, merge ?

**Comment by Shakeskeyboarde** [comment]
1. It use the git CLI, so if you can clone using the `git` command, it can copy from the repo.
2. It always skips files that already exists.
